#config


pretrained_model_path: 'data/pretrained/'
modelname: 'moaiparamdiffusion_model'

dataset:
  root: 'data'
  num_workers: 1
  training_data: ['moai']
  validation_data: ['moai']
  batch_size: 64
  n_images: 4

model:
  use_pretrained: False
  n_shape: 256
  n_exp: 233
  n_rot: 12
  n_pupil: 1
  name: 'moaiparamdiffusion_model'
  with_exp: True
  with_val: False
  with_freeze: 'l4'
  expencoder: 'arcface'

net:
  tag: 'moaiparamdiffusion_archv4_step1000_lr1e3_flame23'
  losstype: 'l1'
  arch: 'archv4'
  moai_dim: 502 
  context_dim: 512

varsched:
  num_steps: 1000
  beta_1: 1e-4
  beta_T: 1e-2
 

train:
  arcface_lr: 1e-4
  diff_lr: 1e-3
  weight_decay: 1e-4
  max_steps: 2000000
  log_steps: 50
  val_steps: 5
  vis_steps: 5000
  val_save_img: 5000
  checkpoint_steps: 1000
  checkpoint_epochs_steps: 300
  #resume: True
  #resume_checkpoint: 'output/config_flameparamdiffusion/best_models/model_train_flameparamdiffusion_archv2_step1000_lr1e3_noval_l3_best.tar' 
